### ISSUE TITLE
CI badges should use correct repo

### ISSUE THREAD

**Issue by tobyink** [uperl/Dist-Zilla-PluginBundle-Author-Plicease#29]
https://github.com/uperl/Dist-Zilla-PluginBundle-Author-Plicease/blob/1dfd04fad2f406b5b28b04348b4a9d9ef18d9727/lib/Dist/Zilla/Plugin/Author/Plicease/ReadmeAnyFromPod.pm#L119

Shouldn't use `$name` here, but `@{[ $self->github_repo ]}`.

**Comment by plicease** [comment]
Yes!  I will see if I can get a fix out before I leave.

**Comment by plicease** [comment]
2.74 should fix this.
